window.__i18n = window.__i18n || {};
window.__i18n.fr = {
  meta: {homeTitle: "Café et repas à Alpendurada, Marco de Canaveses", homeDescription: "Café, petits-déjeuners, repas et en-cas à Alpendurada, Marco de Canaveses. Consultez la carte, les horaires et l’itinéraire.", menuTitle: "Carte", menuDescription: "La carte du Café Avenida à Alpendurada : entrées, plats, snacks et pizzas, desserts, pâtisseries, cafés et boissons, avec les prix."},
  nav: {language: "Langue",backTop: "Retour en haut", home: "Accueil", about: "À propos", gallery: "Galerie", hours: "Horaires", contact: "Contact", location: "Nous trouver", menu: "Carte", main: "Navigation principale", callShort: "Appeler", callLong: "Appeler", skipToContent: "Aller au contenu", openMenu: "Ouvrir le menu", closeMenu: "Fermer le menu", sections: {about: "Le café", gallery: "Galerie", reviews: "Avis", suggestions: "Suggestions", location: "Nous trouver"}},
  hero: {ctaMenu: "Voir la carte", ctaLocation: "Nous trouver"},
  about: {eyebrow: "Le café", title: "À propos de nous", mainRoom: "Salle principale", mainRoomText: "L’espace de notre galerie, pour un café, un repas ou une bonne conversation.", terrace: "Terrasse extérieure", terraceText: "Une pause en plein air, pour savourer l’instant sans se presser.", games: "Salle de jeux", gamesText: "Billard et fléchettes pour défier vos amis et prolonger les bons moments."},
  gallery: {eyebrow: "Les lieux", title: "Galerie", playVideo: "Lire la vidéo", more: "Voir plus de photos", less: "Voir moins"},
  lightbox: {open: "Agrandir la photo", prev: "Photo précédente", next: "Photo suivante", close: "Fermer"},
  reviews: {eyebrow: "Nos clients", title: "Avis", lead: "Ce que l’on dit de nous sur Google.", count: "{count} avis Google", outOf: "{rating} étoiles sur 5", write: "Laisser un avis"},
  suggestions: {eyebrow: "La cuisine", title: "Suggestions", lead: "Des spécialités de la maison à découvrir.", photoSoon: "Photo à venir"},
  hours: {title: "Horaires", eyebrow: "Horaires", openNow: "Ouvert", closedNow: "Fermé", dayNames: ["Dimanche", "Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi"], closed: "Fermé", overnightNote: "* Fermeture dans la nuit du jour suivant."},
  contact: {title: "Contact", phone: "Téléphone", email: "E-mail", call: "Appeler", write: "Envoyer un e-mail", follow: "Réseaux sociaux"},
  location: {title: "Nous trouver", eyebrow: "Nous trouver", directions: "Itinéraire", openMaps: "Ouvrir dans Google Maps", mapCredit: "Carte © OpenStreetMap"},
  footer: {rights: "Tous droits réservés.", menuQr: "Carte numérique", madeBy: "Site créé par", complaints: "Livre de réclamations (Livro de Reclamações)"},
  error: {docTitle: "Page introuvable", eyebrow: "Erreur 404", title: "Cette page n’est pas à la carte", body: "L’adresse est peut-être incorrecte ou le lien n’existe plus. Revenez à l’accueil pour continuer.", home: "Retour à l’accueil", menu: "Voir la carte"},
  menuPage: {categories: "Catégories de la carte",title: "Carte", subtitle: "Choisissez une catégorie", comingSoon: "Du premier café au dessert, faites votre choix.", allergens: "En cas d’allergie ou d’intolérance alimentaire, demandez les informations sur les allergènes au comptoir.", loadError: "Impossible de charger la carte. Vérifiez votre connexion internet et réessayez.", retry: "Réessayer", sizes: {small: "Petite", medium: "Moyenne"}, sizesShort: {small: "P", medium: "M"}, tags: {vegetarian: "Végétarien", glutenFree: "Sans gluten", allergens: "Allergènes"}, empty: "Aucun produit dans cette catégorie.", collapse: "Réduire la catégorie", expand: "Développer la catégorie"},
  qrPrint: {menuLabel: "Carte", scanHint: "Scannez le code avec votre appareil photo"},
  chooser: {open: "Vous hésitez ?", question: "Qu’est-ce qui vous ferait plaisir ?", sweet: "Sucré", snack: "Snack", meal: "Repas", drink: "Boisson", try: "À essayer", another: "Une autre idée", menu: "Voir dans la carte", empty: "De nouvelles suggestions arrivent bientôt.", close: "Fermer les suggestions"}
};
